# Generated by Django 3.2 on 2022-05-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20220525_1626'),
        ('escuelas', '0002_escuela_operativo'),
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('escuela', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela')),
                ('especialidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atenciones.especialidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Atenciones',
            },
        ),
    ]
