# Generated by Django 3.2 on 2022-06-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0003_alter_atencion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='predetarminada',
            field=models.BooleanField(default=False),
        ),
    ]
