# Generated by Django 3.2 on 2022-06-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0004_especialidad_predetarminada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='predetarminada',
            new_name='predeterminada',
        ),
    ]
