# Generated by Django 3.2 on 2022-06-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.unidad'),
        ),
    ]
