# Generated by Django 3.2 on 2022-06-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_escuela_operativo'),
        ('pacientes', '0004_paciente_ayn'),
        ('medicamentos', '0002_medicamento_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('escuela', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.receta')),
            ],
            options={
                'verbose_name_plural': 'Detalles Recetas',
            },
        ),
    ]
