# Generated by Django 3.2 on 2022-06-02 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_escuela_operativo'),
        ('medicamentos', '0004_recetadetalle_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('escuela', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuelas.escuela')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
            options={
                'verbose_name_plural': 'Entregas de Medicamentos',
            },
        ),
    ]
