# Generated by Django 3.2 on 2022-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0006_entregamedicamento_fecha_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Presentaciones Medicas',
            },
        ),
    ]
