# Generated by Django 3.2 on 2022-06-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0007_presentacionmedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.presentacionmedica'),
        ),
    ]
