# Generated by Django 3.2 on 2022-06-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0008_medicamento_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fecha_formulario', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
            options={
                'verbose_name_plural': 'Recepciones de Medicamentos',
            },
        ),
    ]
