# Generated by Django 3.2 on 2022-05-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
